# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of Broker')),
                ('contact', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contact of Broker')),
                ('payment_status', models.CharField(blank=True, choices=[(b'PAID', b'PAID'), (b'UNPAID', b'UNPAID')], default=b'UNPAID', max_length=250, null=True, verbose_name='Payment Status')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Update Date')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker', to='core.Broker')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of Cost')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Update Date')),
            ],
        ),
        migrations.CreateModel(
            name='GarbagePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name of Location')),
                ('type_of_location', models.CharField(blank=True, max_length=250, null=True, verbose_name='Type of Location')),
                ('person_in_charge', models.CharField(blank=True, max_length=250, null=True, verbose_name='Person in Charge')),
                ('contacts', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contacts')),
                ('paper_size', models.CharField(blank=True, choices=[(b'BIG PAPER', b'BIG PAPER'), (b'SMALL PAPER', b'SMALL PAPER')], default=b'SMALL PAPER', max_length=250, null=True, verbose_name='Paper Size')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Update Date')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_area', to='core.GarbagePoint'),
        ),
    ]
