# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'verbose_name': 'Broker', 'verbose_name_plural': 'Brokers'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Collected Garbage Record', 'verbose_name_plural': 'Collected Garbage Records'},
        ),
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': 'Cost', 'verbose_name_plural': 'Costs'},
        ),
        migrations.AlterModelOptions(
            name='garbagepoint',
            options={'verbose_name': 'Garbage Collection Area', 'verbose_name_plural': 'Garbage Collection Areas'},
        ),
    ]
