# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160620_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='collection',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='collection',
            name='payment_status',
            field=models.CharField(blank=True, choices=[(b'PAID', b'PAID'), (b'UNPAID', b'UNPAID')], default=b'UNPAID', max_length=250, null=True, verbose_name='Payment Status'),
        ),
    ]
