# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160620_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagepoint',
            name='number_of_papers',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Number of Papers'),
        ),
    ]
