# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_garbagepoint_number_of_papers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagepoint',
            name='paper_size',
            field=models.CharField(blank=True, choices=[(b'BIG PAPER', b'BIG PAPER'), (b'SMALL PAPER', b'SMALL PAPER')], max_length=250, null=True, verbose_name='Paper Size'),
        ),
    ]
